services:
  postgres:
    image: postgres:16-alpine
    container_name: payments-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost" ]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    image: node:lts
    container_name: payments-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      NODE_ENV: development
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  db_data:
